services:
  {{ image_name }}:
    image: "docker.io/{{ dockerhub_user }}/{{ image_name }}:{{ image_tag }}"
    restart: unless-stopped
    ports:
      - "{{ app_port }}:{{ app_port }}"
    environment:
      DATABASE_URL: "{{ database_url }}"
